kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-akv
      mountPath: "/mnt/secrets-store"
      readOnly: true
        
  volumes:
    - name: secrets-akv
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-provider" 
        nodePublishSecretRef:
          name: akv-creds
