apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "false"
    usePodIdentity: "false"
    userAssignedIdentityID: ""
    subscriptionId: XXXXXXX-XXXX-XXXX-XXXXX-XXXXXX
    tenantId: XXXXXX-3ba0-469fXXXX-XXXXXXX
    resourceGroup: myResourceGroup  
    keyvaultName: AKSKeyVault42489760530
    objects: |
      array:
        - |
            objectName: AKV
            objectType: secret      # object types: secret, key or cert
        - |
            objectName: sapassword
            objectType: secret      # object types: secret, key or cert
